### ISSUE TITLE
Cross ref react-gtk and node-gtk

### ISSUE THREAD

**Issue by codejamninja** [romgrk/node-gtk#103]
Can we cross-reference our repositories to help get more traction around these projects? I believe these two projects are mutually dependant on each other. I would like people to start testing react-gtk so I can start fixing bugs in it. I'm sure it's full of them, and I'm sure I will discover many bugs in this project in the process.

I've already created all of the gtk widgets as react components. There are still many features they are lacking, like events for example. Go take a look at it when you get a chance.

**Comment by codejamninja** [comment]
https://github.com/codejamninja/react-gtk

**Comment by romgrk** [comment]
Sure, ideally something like `react-gtk` would be the recommended approach to develop applications with `node-gtk` (IMHO). Updated in 8c4e3b82bf38303367aed33e94b9d66e583a07fc.

**Comment by codejamninja** [comment]
https://github.com/codejamninja/react-gtk/commit/4fcd798df51378a3f4ae6b74d9ef006f011dcfbf
