### ISSUE TITLE
Arch Linux, Gtk is not defined

### ISSUE THREAD

**Issue by dbdii407** [romgrk/node-gtk#106]
I tried running the hello world example, but I get this error.
https://twitter.com/dbdii407/status/1108764688383467521

I'm on Arch Linux, is there a package that I need to install for this to work?

**Comment by dbdii407** [comment]
I ran the following, however I'm still having the same problem.

`sudo pacman -S --needed base-devel git nodejs npm gtk3 gobject-introspection`

**Comment by romgrk** [comment]
Lol https://twitter.com/dbdii407/status/1108774338122133505 :) I guess you found your issue. Don't hesitate to open issues here to ask questions.
