### ISSUE TITLE
assertion object != null failed

### ISSUE THREAD

**Issue by benwaffle** [romgrk/node-gtk#11]
``` js
const gi = require('node-gtk');
const Pango = gi.require('Pango');

var attrs = new Pango.AttrList();
attrs.insert(new Pango.AttrSize(300));
```

error: `Pango-CRITICAL **: pango_attr_list_insert: assertion 'list != NULL' failed`

**Comment by romgrk** [comment]
duplicate

**Comment by chfritz** [comment]
What is this a duplicate of? I have a similar issue where in various situations I'm not able to create the correct `NULL` object, e.g., to call https://gstreamer.freedesktop.org/documentation/webrtc/index.html?gi-language=javascript#webrtcbin::get-stats with a null pad. I've tried `null`, but with that I get:
```
** (node:10962): CRITICAL **: 12:35:13.471: gst_webrtc_bin_get_stats: assertion 'pad == NULL || GST_IS_WEBRTC_BIN_PAD (pad)' failed
```
So for some reason `null` in JS is not translated to `NULL` in C.

What's the correct way to set a parameter when the C documentation of the gtk method requires `NULL`?

**Comment by romgrk** [comment]
Also it's a different issue, you can open a new issue.
