### ISSUE TITLE
v8 fatal error when running gtk-tree-view.js example

### ISSUE THREAD

**Issue by haijin-development** [romgrk/node-gtk#110]
Hi.

I got a core dumped error when trying to run the tree view example.
I'm using Ubuntu 18.04.

Steps to reproduce the error:

```
git clone https://github.com/romgrk/node-gtk
cd node-gtk/
npm install
node examples/gtk-tree-view.js
```

with the output:

```
FATAL ERROR: v8::Object::SetAlignedPointerInInternalField() Pointer is not aligned
 1: 0x8dc510 node::Abort() [node]
 2: 0x8dc55c  [node]
 3: 0xad993a v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xae5e17 v8::Object::SetAlignedPointerInInternalField(int, void*) [node]
 5: 0x7f389d83c861  [./lib/binding/node-v64-linux-x64/node_gtk.node]
 6: 0x7f389d83c708  [./lib/binding/node-v64-linux-x64/node_gtk.node]
 7: 0xb6166b  [node]
 8: 0xb639cd v8::internal::Builtins::InvokeApiFunction(v8::internal::Isolate*, bool, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*, v8::internal::Handle<v8::internal::HeapObject>) [node]
 9: 0xe73271 v8::internal::Execution::New(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [node]
10: 0xaff436 v8::Function::NewInstanceWithSideEffectType(v8::Local<v8::Context>, int, v8::Local<v8::Value>*, v8::SideEffectType) const [node]
11: 0xaff76c v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const [node]
12: 0x7f389d83d3f4 GNodeJS::WrapperFromBoxed(_GIBaseInfoStub*, void*) [./lib/binding/node-v64-linux-x64/node_gtk.node]
13: 0x7f389d8489eb GNodeJS::GIArgumentToV8(_GIBaseInfoStub*, _GIArgument*, long) [./lib/binding/node-v64-linux-x64/node_gtk.node]
14: 0x7f389d8401ed GNodeJS::FunctionInfo::GetReturnValue(_GIBaseInfoStub*, _GIArgument*, _GIArgument*) [./lib/binding/node-v64-linux-x64/node_gtk.node]
15: 0x7f389d840d77 GNodeJS::FunctionCall(GNodeJS::FunctionInfo*, Nan::FunctionCallbackInfo<v8::Value> const&, _GIArgument*, _GError**) [./lib/binding/node-v64-linux-x64/node_gtk.node]
16: 0x7f389d840f44 GNodeJS::FunctionInvoker(Nan::FunctionCallbackInfo<v8::Value> const&) [./lib/binding/node-v64-linux-x64/node_gtk.node]
17: 0x7f389d83f5a8  [./lib/binding/node-v64-linux-x64/node_gtk.node]
18: 0xb62a3f  [node]
19: 0xb635a9 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
20: 0x293cdf1dbe1d 
Aborted (core dumped)
```

The rest of the examples seem to work just fine.

I'll appreciate any help to workaround this issue.

If its worth knowing it, I want to use `node-gtk` to write a GUI framework in node that somehow resembles React and with that hopefully implement a few simple desktop debugging tools for node.

**Comment by rockiger** [comment]
> If its worth knowing it, I want to use node-gtk to write a GUI framework in node that somehow resembles React and with that hopefully implement a few simple desktop debugging tools for node.

Do you know [react-gtk](https://github.com/codejamninja/react-gtk)? Maybe you can contribute there instead of creating another gui framework.

**Comment by haijin-development** [comment]
I might look at it, thanks.

**Comment by romgrk** [comment]
Got it, I'm able to reproduce the issue.

Behavior only happens when installing with pre-built binary ; build from source works fine.

**Comment by romgrk** [comment]
Not sure what's the issue here but I'll try to merge #115 ASAP, which will create new binaries for version `0.2.3`. If the issue persists then, I'll dig into this.

**Comment by romgrk** [comment]
`0.3.0` has been published, this can be re-visited.

**Comment by romgrk** [comment]
I've tested this again on Ubuntu 19.04 with the `0.3.0` pre-built binary and it works as expected. @haijin-development, can you confirm this is solved for you as well?

**Comment by haijin-development** [comment]
@romgrk Sorry for the delay.
I just tested and it worked perfectly, thanks!

**Comment by romgrk** [comment]
Cool, closing then :) Thanks for reporting!

**Comment by haijin-development** [comment]
It took me some time but the first version of an object browser implemented using `node-gtk` has been published to [npm](https://www.npmjs.com/package/sirens).

I may ask some (or a lot) of questions related to `node-gtk` in the future to add context menus, icons in trees, navigation bars and such.

Thanks again!

**Comment by romgrk** [comment]
No problem, ask as many questions as you want!
