### ISSUE TITLE
missing git tags

### ISSUE THREAD

**Issue by kapouer** [romgrk/node-gtk#114]
Hi, it's useful to do `git tag x.x.x` whenever a version is published to npm, it helps tracking changes between versions.

**Comment by romgrk** [comment]
Isn't it done automagically by `npm version [major/minor/patch]`? Here is the output of my `git tag`:

```
0.0.10
0.0.11
0.0.12
0.0.13
0.0.14
0.0.15
0.0.5
0.0.6
0.0.7
0.0.8
0.0.9
v0.0.1
v0.0.2
v0.0.3
v0.0.4
v0.1.0
v0.1.1
v0.2.0
v0.2.1
v0.2.2
```

**Comment by kapouer** [comment]
good news, you just need to `git push --tags`, unless you configure git (or npm) to sign the tags (in which case `git push` is enough).

**Comment by romgrk** [comment]
Ok, should be done now, thanks!
