### ISSUE TITLE
node-gtk & vue

### ISSUE THREAD

**Issue by subjectdenied** [romgrk/node-gtk#117]
im trying to port vuido (node-libui based vue.js) to node-gtk, and got pretty far, but now i'm stuck at event handling. events are working basically, however inside a vue component method, reactivity only runs after i close the window (destroy it). is it possible this is some issue with the gtk loop, if so do you have a hint how to fix this?

update:
well seems like "setImmediate" does the trick ;-)

**Comment by romgrk** [comment]
Cool, if `setImmediate` works awesome then, otherwise I recommend reading the Gtk C documentation for windows, it's the most appropriate resource. Re-open if you need more assistance.

If you're project is advanced enough, let me know and I'll link to it.
