### ISSUE TITLE
Can't import Granite lib

### ISSUE THREAD

**Issue by drom98** [romgrk/node-gtk#124]
I'm trying to import Granite library but I got this error: 
Failed to load shared library '/build/granite-87hC7Y/granite-5.2.3+r1361+pkg107~ubuntu5.0.1/obj-x86_64-linux-gnu/lib/libgranite.so.5.2.3' referenced by the typelib: /build/granite-87hC7Y/granite-5.2.3+r1361+pkg107~ubuntu5.0.1/obj-x86_64-linux-gnu/lib/libgranite.so.5.2.3: cannot open shared object file: No such file or directory

Using elementary OS Juno.

**Comment by romgrk** [comment]
Closing as duplicate of #97, thanks for the report.
