### ISSUE TITLE
Can't access object properties

### ISSUE THREAD

**Issue by drom98** [romgrk/node-gtk#125]
Hey. Probably this isn't a bug, but I don't know what am I doing wrong.

```js
let searchButton = new Gtk.ToggleButton();
    searchButton.image = new Gtk.Image().fromIconName('edit-find-symbolic', Gtk.IconSize.SMALL_TOOLBAR);
```

Gives me an error: TypeError: (intermediate value).fromIconName is not a function.

**Comment by romgrk** [comment]
Hey! Sorry for the delay, busy week.

So indeed, that function is not a function. We don't have good documentation yet :/ But basically the function is static, it's not an instance method, and it has a slightly different name. Here is the trick:

```js
let searchButton = new Gtk.ToggleButton();
    searchButton.image = Gtk.Image.newFromIconName(
      'edit-find-symbolic',
      Gtk.IconSize.SMALL_TOOLBAR
    );
```

Please re-open if the issue persists!
