### ISSUE TITLE
Make a server on discord

### ISSUE THREAD

**Issue by donnisnoni95** [romgrk/node-gtk#131]
Honestly, I am very happy to contribute to this project. But I need all of you to discuss and sometimes need your help.

It would be nice if we could create a discussion group, so we could discuss with each other. Yes, we have discussed, but not always we continue to discuss on [issues](https://github.com/romgrk/node-gtk/issues).

Thank you... ✌️

**Comment by donnisnoni95** [comment]
Very glad to hear it ... yes I know you must be very busy lately, because I have been waiting a bit longer for your response. 😄
Yes, I really need your guidance and opinions. 🙌

I prefer to use discord, I don't know why 🤔. Maybe because my friends all use Discord, other than that, maybe because now many programming communities have moved to Discord.😄

Come on, register discord account ...😄

Yes, a few days ago, I made the server on Discord, but I deleted it again, because in my opinion it would be more polite, if you as the project owner made the server. ☺️

**Comment by romgrk** [comment]
Oh so apparently I already have a discord account. Great. Well now that you've asked can you re-create it and invite me? ^^

Btw, I don't mind if you take the lead on things, I'm always happy to see people interested in the project.

**Comment by donnisnoni95** [comment]
Good... thank you... Well, I made it, here's the [link](https://discord.gg/r2VqPUV). 
do we have to add the link in readme.md?

**Comment by romgrk** [comment]
Cool, I'm in. We could add a link in the readme, open a PR if you want to.
