### ISSUE TITLE
Is there way to autoconnect signals from glade?

### ISSUE THREAD

**Issue by gavr123456789** [romgrk/node-gtk#140]
I cant find that

**Comment by donnisnoni95** [comment]
Hi @gavr123456789.... 
You can see an example in the [examples](https://github.com/romgrk/node-gtk/tree/master/examples) folder. More precisely in the [`builder.js`](https://github.com/romgrk/node-gtk/blob/master/examples/builder.js) file and the [`builderExample.glade`](https://github.com/romgrk/node-gtk/blob/master/examples/builderExample.glade) file. Thank You... :ok_hand:

**Comment by gavr123456789** [comment]
@donnisnoni95 I know that example, but i mean get handlers signals like that  
![image](https://user-images.githubusercontent.com/30507409/64599309-cf34be80-d3c1-11e9-9761-743287a187e0.png)  
in code:
```
function test(){...}
 ```

**Comment by donnisnoni95** [comment]
So far, to connect between glade and source code automatically, in `C` we can use [`gtk_builder_connect_signals ()`](https://developer.gnome.org/gtk3/stable/GtkBuilder.html#gtk-builder-connect-signals).

Maybe later @romgrk can find a way on the C ++ side.

After seeing this **[PyGobject's API](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Builder.html#Gtk.Builder.connect_signals)**, I tried implementing it on `node-gtk`. I do this by using [`gtk_builder_connect_signals_full ()`](https://developer.gnome.org/gtk3/stable/GtkBuilder.html#gtk-builder-connect-signals-full) which is the same as `Gtk.Builder.connectSignalsFull` on node-gtk.

Try this code, so far it works.
```js
// helper
function connector(builder, object, signal, handler) {
  if (this[handler]) object.connect(signal, this[handler]);
}

function test() {
  console.log("clicked!");
}

builder.connectSignalsFull(connector.bind({ test }));
```

**Comment by donnisnoni95** [comment]
@romgrk Label it as `question` ??

**Comment by romgrk** [comment]
I dont think we need another label, but we migth if we get lots of questions in the future.
Meanwhile, this can be closed as @donnisnoni95 provided an example for this in https://github.com/romgrk/node-gtk/blob/master/examples/builder-auto-connect-signals.js.

Thanks :)
