### ISSUE TITLE
Missing method from Gtk.Builder

### ISSUE THREAD

**Issue by scandinave** [romgrk/node-gtk#151]
Hi,

The Gtk.Builder object are missing method that i need to used.

`console.log(Object.getOwnPropertyNames(Gtk.Builder));`

return : 

`[
  'length',
  'name',
  'arguments',
  'caller',
  'prototype',
  'new',
  'newFromFile',
  'newFromResource',
  'newFromString'
]`

According to this [doc](https://gjs-docs.gnome.org/gtk30~3.24.13/gtk.builder#method-add_from_file), there is lot of methods that are missing. In particular addFromFile that is used to merge multiple glade file into one. 

I was thinking binding was automatic. This is not the case? 

Thx for your work.

**Comment by Drulac** [comment]
I was going to create an issue while I found this one

Same issue using the lib `Vte`. The methods `spawn_sync` and `spawn_async` are missing (they're useful according to the lib documentation https://developer.gnome.org/vte/unstable/VteTerminal.html#vte-terminal-spawn-sync).

Maybe an clue here to resolve the problem : `With the introspectable="0" attribute it won't be used in other bindings generated from the GIR/typelib, for example Python.` (from https://www.bountysource.com/issues/47839811-vala-bindings-for-for-vte-terminal-spawn_async-are-missing)

here a complete code to reproduce :
```js
const gi = require('node-gtk')

const Gtk = gi.require('Gtk', '3.0')
const Vte = gi.require('Vte')
const GLib = gi.require('GLib')

// Start the GLib event loop
gi.startLoop()

Gtk.init()
const window = new Gtk.Window({
	type: Gtk.WindowType.TOPLEVEL
})

const terminal = new Vte.Terminal('/usr/bin/nvim')

terminal.setInputEnabled(true)

terminal.spawn_sync(
	Vte.PtyFlags.DEFAULT,
	require('os').homedir(),
	['/bin/sh'],
	[],
	GLib.SpawnFlags.DO_NOT_REAP_CHILD
	//null,
	//null
)

window.add(terminal)

window.on('show', () => Gtk.main())
window.on('destroy', () => Gtk.mainQuit())
window.on('delete-event', () => false)

window.showAll()
```

this code produce : 
```
terminal.spawn_sync()
         ^

TypeError: terminal.spawn_sync is not a function
    at Object.<anonymous> (term.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by romgrk** [comment]
@Drulac `node-gtk` uses the usual javascript conventions for naming, which means camelCase for functions. For more details check the [Naming conventions](https://github.com/romgrk/node-gtk#naming-conventions) section.

**Comment by romgrk** [comment]
@scandinave Actually, the method is there, but it's a *non-static* method, which means that it's available on the instances of `Gtk.Builder`, not on the class itself. I understand the confusion though! Be cautious when referring to GJS doc because it might be subtly different from `node-gtk` :/ They however mention the static/non-static status on the TOC at the top of the page.

`console.log(Object.getOwnPropertyNames(Gtk.Builder.prototype))`
Logs:
```
[
  'constructor',
  'translationDomain',
  'addCallbackSymbol',
  'addFromFile',
  'addFromResource',
  'addFromString',
  'addObjectsFromFile',
  'addObjectsFromResource',
  'addObjectsFromString',
  'connectSignals',
  'connectSignalsFull',
  'exposeObject',
  'extendWithTemplate',
  'getApplication',
  'getObject',
  'getObjects',
  'getTranslationDomain',
  'getTypeFromName',
  'setApplication',
  'setTranslationDomain',
  'valueFromString',
  'valueFromStringType'
]
```

**Comment by scandinave** [comment]
Oh nice. Thx for this quick anwser.

**Comment by Drulac** [comment]
Oh yeah I've forgot to convert to camelCase. But wen I run `terminal.spawnSync` I'm getting a segmentation error. Maybe it's me wich don't provide rights arguments. I'm investigating this option.

**Comment by romgrk** [comment]
>  But wen I run `terminal.spawnSync` I'm getting a segmentation error. Maybe it's me wich don't provide rights arguments. I'm investigating this option.

@Drulac if so, could you open a separate issue and provide all the details leading to the segfault? Thanks!

**Comment by Drulac** [comment]
Maybe the formating wasn't explicite, I've edited my message with a working code (for potential futurs persons), the problem was on my side 😉
