### ISSUE TITLE
Segmentation fault when using Builder.addFromFile

### ISSUE THREAD

**Issue by scandinave** [romgrk/node-gtk#154]
HI,
 
I'm trying to load a template file with the method `addFromFile` 

```
import gi from 'node-gtk';
const Gtk = gi.require('Gtk', '3.0');
import path from 'path';
const __dirname = path.resolve();

const builder = new Gtk.Builder();
builder.addFromFile(path.join(__dirname, './src/window.ui'));
```

window.ui
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.22.1 -->
<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkApplicationWindow" id="MyApp">
    <property name="name">my-app</property>
    <property name="can_focus">False</property>
    <property name="startup_id">myapp</property>
    <child>
      <placeholder/>
    </child>
  </object>
</interface>
```

when i run node --experimental-modules src/builder.js, i got a segmentation fault error. 

I use Node 12x

**Comment by romgrk** [comment]
Yes, the Gtk library requires you to initialize it before usage, and this project needs you to start the event loop yourself, so you always need to prefix usage of Gtk with:

```js
gi.startLoop()
Gtk.init()
// Gdk.init([])
```

Not very user-friendly but this is basically just a C library being called from javascript, so there is not much sugar-coating :/
