### ISSUE TITLE
Question about usage with lisp layer on top of node.js

### ISSUE THREAD

**Issue by jcubic** [romgrk/node-gtk#170]
I have a question, not sure if it's right place to ask, I have not standard setup. I'm running your project inside scheme (lisp) interpreter written in JavaScript in node.js but I have issue with creating demo app. It seems that it create window but without the label and background from behind the window stay when I move the window.

![node-gtk](https://user-images.githubusercontent.com/280241/78188496-9d279e80-7470-11ea-86eb-92aed78d6727.png)

Do you know how to debug this or know why it don't render the label? Setting window dimensions seems to work.

If you're interested in helping me I can create repo where you can run the code (or branch in my scheme interpreter) If I will be able to run node-gtk inside scheme inside node.js I may write some article or maybe tweet about this or write on reddit on /r/scheme.

I'm still working on my interpreter I'm creating the label like this:

```scheme
(define label (new Gtk.Label (make-object :label "Hello Scheme GTK+")))
(win.add label)
```

this is 1-1 transformation of the demo code into scheme. I was testing `new` function and `make-object` and everything seems to be correct with them.

Any ideas what may went wrong?

**Comment by romgrk** [comment]
Hey,

I'd need to see the actual code to be able to give you feedback. If you're doing a 1-1 transformation to javascript, you should be able to run the examples by translating the javascript in lisp. The window does require at least one child.

Post a gist of your lisp code and I'll take a look.

Thanks

**Comment by jcubic** [comment]
I've created branch in scheme/lisp code repo https://github.com/jcubic/lips/tree/node-gtk 

The interpreter have debug console logs, it seems that `new` return proper GtkLabel and make-object return proper object with string.

I would really appreciated if you could take a look.

In my interpreter method call `win.add(x)` is written in `(win.add x)` it will get add from win use bind with win and the call it same as `win.add.call(win, x)` this works in JS.

**Comment by romgrk** [comment]
Ok, so I've taken a look and I'm not sure what the issue could be. So you're saying the JS version works but not the SCM one? In that case my guess would be it's not being translated properly. Are you able to generate the JS output of the SCM code?

**Comment by jcubic** [comment]
I can't generate JS code because my Scheme is interpreter. 

Ok I was able to run the code from REPL so maybe the content of the window get garbage collected, I think that it can't be by node because Scheme variables are saved in object, so there are always a reference, here is the code for the REPL that execute when you call ./run.scm:

```javascript
if (options._.length === 1) {
    fs.readFile(options._[0], function(err, data) {
        var e = env.inherit('name');
        if (err) {
            console.error(err);
        } else {
            boostrap(e).then(function() {
                return run(data.toString().replace(/^#!.*\n/, ''), e);
            })
        }
    });
}
```

Maybe it's some internal GTK+ or Node.js thing. I have no idea why code copy pasted into repl works but not from script.

**Comment by jcubic** [comment]
I'm closing the issue, this is something with node.js. Adding:
```javascript
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });
```
at the beginning fixed the issue, don't know why maybe will got answer on SO.

Thanks for you time.
