### ISSUE TITLE
How to package applications

### ISSUE THREAD

**Issue by mabhishek7081** [romgrk/node-gtk#178]
Awrsome project. But i want to know that how package applications in .deb or as flatpacks

**Comment by WebReflection** [comment]
I guess you need to define a list of possible dependencies, which starts with nodejs, Gtk3+ and object-introspection, but it can span across various Gtk related projects, including WebKit2Gtk, as example, if you'd like to show a _WebView_ in your project.

**Comment by romgrk** [comment]
As @WebReflection said, you need the list of deps. The node-gtk dependencies for popular distributions are listed in the installation section of the readme. Beyond that you need the dependencies for your own application, which include the libraries plus the GIR (gobject-introspection) files to interact with them.

For example, on Debian, if your application `gi.requires('Granite')`, you'll need the package `libgranite5` which is the library, plus the `gir1.2-granite-1.0` package (most GIR files are in a package named `gir1.2-xxxxxxx-x.x`).

Ideally it would be nice to be able to package a node-gtk app as simply as an electron app, but I haven't explored the packaging options yet :/

Let me know if anything is unclear or you need more assistance.

**Comment by msooraj9452** [comment]
### Thanks to you both . 
I got a basic idea if you can make and upload demo project it will be really helpful.
no worries if not possible .
Thanks for this awesome project will love to contribute it this :)

**Comment by mabhishek7081** [comment]
### Thanks to you both .
I got a basic idea if you can make and upload demo project it will be really helpful.
no worries if not possible .
Thanks for this awesome project will love to contribute it this :)
