### ISSUE TITLE
Segfault on creating non-introspected object

### ISSUE THREAD

**Issue by wotzlaff** [romgrk/node-gtk#179]
I tried to start the simple gstreamer example located in examples/gst.js and is segfaults. When I tried to figure out where it comes from I started digging into your code. Actually, I'm no expert on GObject Introspection and these things. So I hope, I could pinpoint the issue to its source and provide enough information:

Segfault happens when creating a new `GstElement`, namely `GstVideoTestSrc`, here:
https://github.com/romgrk/node-gtk/blob/f7b917b9af8fc4520829affb414a1595cbc0a55d/examples/gst.js#L17

Debugging led me to the problem here:
https://github.com/romgrk/node-gtk/blob/f7b917b9af8fc4520829affb414a1595cbc0a55d/src/gobject.cc#L513-L516

At the first line, `gtype` is `GstVideoTestSrc` (non-introspected?). Hence, the result of the next line (`realInfo`) is nullptr. And the Segfault finally happens here, where `gtype` is null (i.e. `G_TYPE_INVALID`): https://github.com/romgrk/node-gtk/blob/f7b917b9af8fc4520829affb414a1595cbc0a55d/src/gobject.cc#L457

Maybe the check at https://github.com/romgrk/node-gtk/blob/f7b917b9af8fc4520829affb414a1595cbc0a55d/src/gobject.cc#L479-L483 is not sufficient?

The issue has been introduced in https://github.com/romgrk/node-gtk/commit/375712cf76145a68a8135a321db874aa08f5e8d7. The problem might be related to the previous discussion in #74.

I'd love to use your awesome package to create some gstreamer application :)

**Comment by romgrk** [comment]
Thanks for the detailed report :)
One question, what makes you think that the issue was introduced in 375712c? (Haven't looked at the issue yet, will debug maybe this weeked if I have some time)

**Comment by wotzlaff** [comment]
Actually, I have no idea why the changes in https://github.com/romgrk/node-gtk/commit/375712cf76145a68a8135a321db874aa08f5e8d7 broke things. But undoing the part of the commit which changed the lines above seems to fix the issue (see [my fork](https://github.com/wotzlaff/node-gtk)). Since I'm not pretty sure that this is a true solution, I wanted you to have a look on it.

BTW: I'm currently collecting the issues when using gstreamer (in the [basic tutorials](https://github.com/wotzlaff/node-gstreamer-tutorial)). I hope to be able to fix these and pull it back to your repo. In order to do this I still need some time to get into introspection which seems not to be very well documented...

**Comment by romgrk** [comment]
@wotzlaff ok! Btw you can open all the issues on this repo, it will help to keep track of them :)

**Comment by wotzlaff** [comment]
It seems to be fixed now. Thanks for pulling.
You'll get some of the issues when I'm sure that these are real issues and not due to my missing knowledge.

**Comment by romgrk** [comment]
Sure, but don't hesitate to open even if you're unsure, I can answer your questions as much as I can. I'd be happy to share my knowledge, documentation for the GIR project is very sparse :/
