### ISSUE TITLE
Output parameters of type enum are not handled correctly

### ISSUE THREAD

**Issue by wotzlaff** [romgrk/node-gtk#185]
Again, the issue comes from trying to use GStreamer.

When there are functions with enum out arguments, the return values have not the right values. We're getting some pointer values instead of the right integers.
You can observe the issue in [this example](https://github.com/wotzlaff/node-gstreamer-tutorial/blob/28c91135aaeea123281f436c5090aeff74bb85d0/src/tutorial-1.js#L30). On line 30 we should get three enum values of type GstState.

I think there is something wrong [here](https://github.com/romgrk/node-gtk/blob/master/src/function.cc#L587-L593). The enum return values fall into the first case. But taking the pointer gives one more level of indirection which is wrong. [Later on](https://github.com/romgrk/node-gtk/blob/master/src/value.cc#L136) (basically) the value of the pointer is read instead of the value itself. I am not sure whether the problem only affects `GI_INFO_TYPE_ENUM` and `GI_INFO_TYPE_FLAGS`, but the solution would be not to take the reference for these two types.
Moreover, there could be a problem with taking `arg->v_long`. At least, the guys at PyGObject are using `v_int` or `v_uint` [here](https://gitlab.gnome.org/GNOME/pygobject/-/blob/master/gi/pygi-argument.c#L816-847).

Edit: Removing the first case (i.e. setting `isPointer = false`) helps to get the right values.

**Comment by romgrk** [comment]
I've pushed a some commits directly to master to apply the fix you described, you example works with them. Still need to add tests for this though.

You might need to merge/rebase your PR against master.
