### ISSUE TITLE
Output parameters of type struct yield segfault

### ISSUE THREAD

**Issue by wotzlaff** [romgrk/node-gtk#189]
This problem is similar to #185. There is still some problem around [here](https://github.com/romgrk/node-gtk/blob/master/src/function.cc#L603-L609).

Here's some example:
```js
const gi = require('node-gtk')
const GstSdp = gi.require('GstSdp')

const sdp = 'v=0'
const [res0, msg] = GstSdp.sdpMessageNewFromText(sdp)
console.log(res0, msg, msg.asText())
const [res1, msgCopy] = msg.copy()
console.log(res1, msgCopy, msgCopy.asText())
```
The function `msg.copy` should deliver a copy. But it segfaults. The problem comes from the function `GstSdp.sdpMessageNewFromText` (see [`gst_sdp_message_new_from_text`](https://gstreamer.freedesktop.org/documentation/sdp/gstsdpmessage.html#gst_sdp_message_new_from_text)) which has some struct (of type `GstSDPMessage`) as an output argument.

This is working:
```cpp
if (IsPointerType(&arg_type) && g_arg_info_is_caller_allocates(&arg_info)) {
    void *pointer = &arg_value.v_pointer;
    ADD_RETURN (GIArgumentToV8(&arg_type, (GIArgument*) pointer))
}
else {
    ADD_RETURN (GIArgumentToV8(&arg_type, (GIArgument*) arg_value.v_pointer))
}
```
But probably there's some deeper problem with the value of `IsPointer`. So this fix is only scratching the surface.

**Comment by romgrk** [comment]
Yes, there are likely probably problems under the surface, GIR is underdocumented so `function.cc` is a big guesswork of how the GIR API should be used -_-

Do you want to open a PR with that test? Lmk, I might have time to work on it this weekend I could make the change.
