### ISSUE TITLE
npm audit shows vulnerabilities regarding nid-parser

### ISSUE THREAD

**Issue by susurri** [romgrk/node-gtk#191]
`npm audit` shows `found 2 vulnerabilities (1 low, 1 moderate) `
as `nid-parser` depends on vulnerable version of  `minimist` and `extend`.

`nid-parser` has not been maintained for years and should not be used.

**Comment by romgrk** [comment]
Seems irrelevant, `nid-parser` never receives dynamic input. Do you see an attack vector?

`nid-parser` seems to be doing its job fine, it doesn't need to be maintained if it works.

**Comment by romgrk** [comment]
After inspection, I've found no threat from using `nid-parser`. It should be noted that it never runs automatically, only manually during development. This with the fact that it doesn't received dynamic input is enough to ignore the warnings.

**Comment by romgrk** [comment]
One thing though, `nid-parser` will be moved to `devDependencies`, won't be installed on users' machines anymore.
