### ISSUE TITLE
invaild value error 

### ISSUE THREAD

**Issue by mabhishek7081** [romgrk/node-gtk#196]
how to fix this ?
```
/home/abhishek/Projects/node-gtk/main.js:40
 stackSwitcher.setHalign("GTK_ALIGN_START");
               ```

TypeError: Expected argument of type Gtk.Align for parameter align, got 'GTK_ALIGN_START'

**Comment by wotzlaff** [comment]
Try to use `Gtk.Align.START` instead of `"GTK_ALIGN_START"`.

**Comment by mabhishek7081** [comment]
it works Thanks!
