### ISSUE TITLE
Values returned from function with enum out arguments are wrong

### ISSUE THREAD

**Issue by peat-psuwit** [romgrk/node-gtk#208]
[gst_element_get_state](https://gstreamer.freedesktop.org/documentation/gstreamer/gstelement.html?gi-language=c#gst_element_get_state) has the folowing signature, where `GstState` is an enum and `state` and `pending` are out arguments.
```c
GstStateChangeReturn
gst_element_get_state (GstElement * element,
                       GstState * state,
                       GstState * pending,
                       GstClockTime timeout)
```

In GJs, the following code returns the correct output, `1,1,0`.
```js
const Gst = imports.gi.Gst;

Gst.init(null);

const pipeline = Gst.parse_launch('videotestsrc ! videoconvert ! autovideosink');
print(pipeline.get_state(Gst.SECOND)); // 1,1,0
```

However, the equivalent code in node-gtk doesn't give the correct output.
```js
const gi = require('node-gtk');
const Gst = gi.require('Gst', '1.0');

Gst.init(null);

const pipeline = Gst.parseLaunch('videotestsrc ! videoconvert ! autovideosink');
console.log(pipeline.getState(Gst.SECOND)); //[ 1, 55150264, 55150288 ]
```

The big numbers change with each run and look a lot like a pointer. I've attached a debugger and try to de-reference it, and it seems to dereference to an expected number.

**Comment by wotzlaff** [comment]
This issue was fixed recently. However, the releases on npm are not up-to-date.
If you need the bugfix, clone the repo and build it from source until the new release is available.

**Comment by peat-psuwit** [comment]
Yes, you're right. Sorry for the noise.

// Note to self: will always check the development release from now on...
