### ISSUE TITLE
Setting css provider for screen

### ISSUE THREAD

**Issue by docb** [romgrk/node-gtk#211]
hi i attempted to port the following snippet:

```c
GtkCssProvider* Provider = gtk_css_provider_new();
GdkDisplay* Display = gdk_display_get_default();
GdkScreen* Screen = gdk_display_get_default_screen(Display);

gtk_style_context_add_provider_for_screen(Screen, GTK_STYLE_PROVIDER(Provider), GTK_STYLE_PROVIDER_PRIORITY_USER);
gtk_css_provider_load_from_path(GTK_CSS_PROVIDER(Provider), "styles.css", NULL);
```

my best guess was:

```js
Gdk.init([]);
Gtk.init();
console.log("get default display");
const display = Gdk.Display.getDefault();
//const display = Gdk.Display.open(":1.0");  --- doesn't work either
console.log("get default screen");
const screen = display.getDefaultScreen();
console.log("get css provider");
const css = new Gtk.CssProvider();
console.log("load css");
css.loadFromPath(Path.join(__dirname+'/lib', 'style.css'));
console.log("add css provider for screen");
Gtk.StyleContext.addProviderForScreen(screen,css,1);
```

but it fails when trying to get the display (node-gtk 0.4.0, node 10.22,  ubuntu 18.04):

get default display

```
** (node:16234): CRITICAL **: 17:30:23.778: g_registered_type_info_get_g_type: assertion 'info != NULL' failed

(node:16234): GLib-GObject-CRITICAL **: 17:30:23.778: g_type_get_qdata: assertion 'node != NULL' failed
Segmentation fault (core dumped)
```

may be you can provide a working code or identify a bug.

Btw: Thanks for this great initiative!

**Comment by romgrk** [comment]
Hey, I've tried running your code as-is (adding the missing require() calls) and it works for me. So I'd say first question would be, are you able to run that C example you listed? If it can't run, we already know the problem isn't in node-gtk but is elsewhere. You seem to mention that you can't get the default display, I've seen that happen when the code is run in an environment where no graphical mode session is present. What is the output if you run `echo $DISPLAY`? And does your code run if you run it with `xvfb-run node file.js`? (`xvfb-run` is a virtual X server, you'll probably need to install it via your package manager)

![Screenshot from 2020-09-12 21-32-32](https://user-images.githubusercontent.com/1423607/93008117-4229c580-f53f-11ea-9eb2-5175a79d3e8c.png)

**Comment by docb** [comment]
hi, the c code is running fine. 
and i assume the display is also found, because i tested the following:
const display = Gdk.Display.open(":1.0")   with the same error message (":1.0" is the value of the env DISPLAY)
if i pass with intent a wrong display e.g. ":0.0" the i get a different but expected error message
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
and the method returns null (so no segfault)
i didn't get xfvb-run work so far neither with the c code  (does not display the window) nor with the node-gtk code - here comes:
 Unable to init server: Could not connect: Connection refused
would have to dive in here ...
may be running an Xfce desktop could be an issue on my side.

**Comment by romgrk** [comment]
Ooooooh ok I think I know what it is. Normally all dependencies of a GIR module are automatically loaded. However I think it's not possible to make them dependent on the environment, thus for `Gdk` there is an additional dependency for X11 that isn't loaded automatically. Try running with `gi.require('GdkX11', 'same version as gdk')`

I run under Wayland, that's why I couldn't reproduce.

**Comment by docb** [comment]
Yep, Thanks. That works!

**Comment by romgrk** [comment]
Cool, I've also added a [section](https://github.com/romgrk/node-gtk#common-pitfalls) about this in the readme.
