### ISSUE TITLE
Testing callback fails on macOS

### ISSUE THREAD

**Issue by wotzlaff** [romgrk/node-gtk#232]
We found this in #230.

`tests/callback.js` fails.
From travis logs there is no obvious reason. Running the test with `GST_DEBUG=3` tells us that the `webrtcbin` element is missing. This is probably due to some missing dependency.

**Comment by WebReflection** [comment]
FYI after a `brew install gst-plugins-bad` the error count is now down to 3 and `test/callback.js` is green.

**Comment by wotzlaff** [comment]
Thanks for that comment.
I think we are missing `gst-plugins-good` in the dependencies for travis.

**Comment by WebReflection** [comment]
does good also include `webrtcbin` ? I can check if you like

**Comment by WebReflection** [comment]
just tested, it doesn't, with `gst-plugins-good` the callback test is red again :-(

**Comment by WebReflection** [comment]
also first time it's slow due `gst-plugins-scanner` taking its first time to grab it, yet with `-bad` all it's good again in here.

**Comment by wotzlaff** [comment]
On my system I needed `-good` and `-bad` for the tests to succeed. Travis is still failing and I am trying to find out what's wrong there.

**Comment by wotzlaff** [comment]
The problem at travis is still that `webrtcbin` is missing: https://travis-ci.com/github/wotzlaff/node-gtk/jobs/417640689#L6220
Maybe I should try it locally on High Sierra again.
