### ISSUE TITLE
g_base64_decode fails (function out parameters)

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#235]
```javascript
const GLib = gi.require('GLib', '2.0');

const data = 'aGVsbG8='
const result = GLib.base64Decode(data, data.length)
// keeps running for a while; `out_len` parameter is likely corrupted because it returns a huge number 
```

**Comment by wotzlaff** [comment]
I can confirm that `GLib.base64Decode` is not working. But it is not inout either.
The function `GLib.base64DecodeInplace` would be. I am not sure whether char arrays with inout property will be handled correctly as strings allocated in js should probably not be modified from the outside. But maybe we are already copying in this case.

**Comment by wotzlaff** [comment]
The problem in the example is (see https://developer.gnome.org/glib/stable/glib-Base64-Encoding.html#g-base64-decode):
> Note that the returned binary data is not necessarily zero-terminated, so it should not be used as a character string.

I think that we expect a zero-terminated string. So waiting for some zero in a random sequence of bytes takes some time. We need to use the output argument to determine the length instead.

**Comment by romgrk** [comment]
We were just not handling the `array-length` annotation for out-parameters in `FunctionCall`. The PR addresses that and adds test.
