### ISSUE TITLE
Gst.Promise.new_with_change_func missing

### ISSUE THREAD

**Issue by billylindeman** [romgrk/node-gtk#244]
I'm trying to use Gst promises and I don't see this function as available.  Not sure why it is missing.  Any help would be appreciated! @sdroege any ideas?

**Comment by romgrk** [comment]
node-gtk follows javascript naming conventions (unlike gjs), if you're looking with that name you'll not find it. The example below runs correctly on my side, please reopen the issue if it's not working for you.

```js
const gi = require('node-gtk')
const Gst = gi.require('Gst')
const p = Gst.Promise.newWithChangeFunc(() => console.log('test'))
const s = Gst.Structure.newFromString('structure')
p.reply(s)
```

**Comment by billylindeman** [comment]
Thanks for the quick response, this is very helpful!
