### ISSUE TITLE
Support GTK 4.0

### ISSUE THREAD

**Issue by binyamin** [romgrk/node-gtk#250]
Even though [GTK 4.0 was just released yesterday](https://blog.gtk.org/2020/12/16/gtk-4-0/) :smiley:, it's probably smart to have an open issue about this.

**Comment by romgrk** [comment]
As far as node-gtk is concerned, you only need to `gi.require('Gtk', '4.0')` to use it, this is a gobject-introspection package more than a GTK package, the name isn't the best pick. I'll close but if you find specific issues with Gtk 4, please reopen or file them individually. Thanks.

**Comment by WebReflection** [comment]
FWIW in Rust case they had to update some binding ... so keeping an eye that GObject actually works as expected with v4 might be good https://github.com/gtk-rs/gtk4-rs

**Comment by binyamin** [comment]
@romgrk about the name - how about `node-gi`?

**Comment by WebReflection** [comment]
there's a node-gir module which would likely conflict with node-gi or nodegi, and as node-gtk users are mostly interested in using libraries around Gtk, I think the name is just fine and not worth the change at this point, for what it matters.

**Comment by romgrk** [comment]
I concur with Andrea, there already has been a discussion around that. Conclusion was: it would be nice, I'm not strongly opposed, but it's likely not worth the hassle.
