### ISSUE TITLE
Build node-gtk in termux 

### ISSUE THREAD

**Issue by Yisus7u7** [romgrk/node-gtk#254]
Termux has a desktop with support (xfce4) and libraries like gtk2, gtk3, python2/3 ruby, nodeJS and what you need, I want to develop windows For the desktop x11, and tried with others Languages and does not work, with java script hosts a few problems, I would like you to do a node-gtk construction for termux, I would thank you very much, good day

**Comment by wotzlaff** [comment]
This is probably not working as termux does not support `gobject-introspection`, yet (see https://github.com/termux/x11-packages/issues/81).
Even if this issue is resolved I would expect it to be not straightforward because of other dependencies.

**Comment by Yisus7u7** [comment]
So, it's not possible to make graphic apps in the with nodeJS?, I would very much like that idea, to a that are web code-based apps, but, there is no way to make a window for x11-termux?

**Comment by WebReflection** [comment]
@Yisus7u7 this project, pretty much like any other *gir* based one, requires `gobject-introspection`, so it looks like you're filing an issue in the wrong repository ;-)

**Comment by Yisus7u7** [comment]
Well, maybe I already switched to python, since termux if you ran tkinter and pysimplegui windows, and I tried the tkinter version that's in npm repo and it also worked, anyway thank you for everything

**Comment by romgrk** [comment]
Sorry for the delay, I'm happy you found a resolution with another project, tbh termux isn't an environment that I would try to support at the moment.
