### ISSUE TITLE
Name of WebKit2.WebView.is-loading property

### ISSUE THREAD

**Issue by JumpLink** [romgrk/node-gtk#256]
Methods and properties are both renamed to `lowerCamelCase`.

`WebKit2.WebView` has a property called `is-loading` and a method `is_loading`, in [this example](https://github.com/sammydre/ts-for-gjs/blob/master/examples/node-gtk/browser/main.ts) the WebView has the method `isLoading()` but what is the name of the `is-loading` property? Could it be that property has the same name and was overwritten by the method?

**Comment by romgrk** [comment]
Yes, that is one issue with the current naming conventions, some boolean properties are overwritten. You can use [GObject.prototype.setProperty](https://github.com/romgrk/node-gtk/blob/master/lib/overrides/GObject.js#L42-L44) to set the property.

I'll close as this is the intended behavior for node-gtk, the slight inconvenience of losing those properties is vastly compensated by being able to use idiomatic javascript conventions for everything else.
