### ISSUE TITLE
Support unions

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#3]
In `lib/index.js :: makeInfo`, when `type == GI_INFO_TYPE_STRUCT` or `type == GI_INFO_TYPE_UNION`.

**Comment by romgrk** [comment]
Implemented for structs. 
Unions: need to clarify how the hierarchy of prototypes would work for these. Works but only if the prototype is directly assigned. (eg `myUnion.__proto__ = Gdk.Event;`)

**Comment by romgrk** [comment]
For unions, a way to go would be that the Union prototype has getters for each possibility.
The struct constructers would however need to handle the case when they're called with a ref to the original union. (they would share the underlying data)
```typescript
class GdkEvent {
  type: GdkEventType;

  get key(): GdkEventKey {
    return new GdkEventKey(this);
  }
  get scroll(): GdkEventScroll {
    return new GdkEventScroll(this);
  }

  // ...
}
```

**Comment by WebReflection** [comment]
I wonder if a Proxy as prototype would work better than that

**Comment by romgrk** [comment]
Ideally, I would like the following relations to work:
```js
input.connect('key-press-event', (widget, event) => {
  const keyEvent = event.key
  console.assert(event instanceof Gdk.Event)
  console.assert(keyEvent instanceof Gdk.Event)
  console.assert(keyEvent instanceof Gdk.EventKey)
  // which implies
  console.assert(Gdk.EventKey.__proto__ === Gdk.Event)
})
```

IMO, a proxy would add an unnecessary level of indirection.

**Comment by romgrk** [comment]
So the above relations will not work, because `GdkEventKey` is not a GObject, so there's no parent-child relation with `GdkEvent`. 
Also, unions & structs complex fields are not supposed to work with bindings. Anything that requires memory management must be get/set through a function. Which means that we're done here, because unions already work as expected :D
