### ISSUE TITLE
Need help in understanding templates

### ISSUE THREAD

**Issue by rexkogitans** [romgrk/node-gtk#312]
Gtk 4 now uses templates to connect the event handlers mentioned in an XML UI file automatically. However, I need some help to understand how to do in JS. This is what I have come up with so far:

````
#!/usr/bin/env node

const gi = require('node-gtk')
const GLib = gi.require('GLib', '2.0')
const Gtk = gi.require('Gtk', '4.0')

class Foo extends Gtk.Box {
    
    GTypeName = "example1"
    __gtype__ = "example1"  // I think that this is correct
    #btn_hello = null;
    
    constructor() {
        let xml = `<interface>
  <template class="example1" parent="GtkBox">
    <child>
      <object class="GtkButton" id="hello_button">
        <property name="label">Hello World</property>
        <signal name="clicked" handler="btn_hello_clicked" swapped="no" />
      </object>
    </child>
  </template>
</interface>
`
        super()
        this.setTemplate(xml)  // does not work
        //this.initTemplate()
    }
    
    btn_hello_clicked() {
        console.log("btn clicked")
    }
    
}

var myapp = null;

function onActivate() {
    myapp = new Foo()
}


const loop = GLib.MainLoop.new(null, false)
const app = new Gtk.Application("rexkogitans.mwe-node-gtk", 0)
app.on('activate', onActivate)
const status = app.run([])

gi.startLoop()

loop.run()
````

Can someone tell me what to do exactly in the constructor to load the XML UI data and connect the event handlers automatically?

Kind regards

**Comment by binyamin** [comment]
@rexkogitans I'm not sure exactly how it would be done, correctly. As it happens, there seems to be a bug making it so that the relevant methods don't exist.

---
@romgrk This is related to #283 (see later comments), where some methods aren't exposed

**Comment by rexkogitans** [comment]
I tried to overly expose everything, but as I lack in time I could not go into deeper. In bootstrap.js, line 382 says
````
return undefined;
````
I replaced it by
````
return makeObject(info);
````
Running the program I got a gazillions of errors of this form:
````
Couldn't load Gtk.NativeDialogClass: (null)
Couldn't load Gtk.NativeInterface: (null)
Couldn't load Gtk.NeverTriggerClass: (null)
````
ending in the completely nonsensial message:
````
/home/rexkogitans/Programmierung/node-gtk/lib/overrides/Gtk-4.0.js:113
  Gtk.Builder.prototype.constructor() {
                                      ^

SyntaxError: Unexpected token '{'
````
Also, I do not understand what this means (maybe I lack in understanding of JS here):
````
function makeObject(info) {
  const constructor = tryCall(internal.MakeObjectClass, info);
````
... or is `constructor` here just an unfortunate identifier, because usually I know this as the name of the special method which serves as constructor within a class.

**Comment by rexkogitans** [comment]
Addendum; IMHO, the equivalent to pyobject's `gi/_gtktemplate.py` is missing.

**Comment by romgrk** [comment]
For now, there is no equivalent. PyGObject does some magic to make templates work, we're not at that stage yet.

To create a GTK4 application, the best model for now is [node-gtk-template](https://github.com/romgrk/node-gtk-template), in particular [window.js](https://github.com/romgrk/node-gtk-template/blob/master/src/window.js) for your use case.

Closing but don't hesitate if you have more questions.
