### ISSUE TITLE
Fix license issues

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#34]
Some functions are copied from PyGObject, which is LGPL, incompatible with our license. We need to remove those.

**Comment by WebReflection** [comment]
you should ask @magnus about it, he's the one that put a license in this project

**Comment by WebReflection** [comment]
* @magcius

**Comment by magcius** [comment]
None of my code was copied from PyGObject. I already relicensed all of the code I wrote to MIT.

**Comment by WebReflection** [comment]
then @romgrk probably meant some of the new functions, apologies for the confusion @magcius (I guess I thought better safe than sorry).

**Comment by romgrk** [comment]
No, it's about new functions ([GIArgumentToHashPointer, HashPointerToGIArgument](https://github.com/romgrk/node-gtk/blob/master/src/value.cc#L29-L91)) that were taken with no modifications. They're essentially switch cases, hard to implement otherwise but I want to make sure we're safe.

**Comment by romgrk** [comment]
https://gitlab.gnome.org/GNOME/pygobject/issues/234

**Comment by b3u** [comment]
@romgrk as this issue is resolved on gitlab, maybe this issue should be closed here as well?
