### ISSUE TITLE
Documentatin bug?

### ISSUE THREAD

**Issue by PopeNobody** [romgrk/node-gtk#342]
The building instructions for Ubuntu said to do some apt-gets, and then "npm install node-gtk"

This did not work for me.  It complained it could not find '*.node" files when I tried to run even the "hello world" example.

However, when I just did "npm install"  in the root of what I had gotten from git, it did work, and I was able to fire up the browser example.

Hope his is helpful to somebody.

**Comment by PopeNobody** [comment]
Well, I goota say, this is the bee's knees.

Usually example browsers are luky to render a hunk of html properly.

This this looks beautiful, and I logged into githup with ti to make this comment.

Nifty!

**Comment by binyamin** [comment]
@PopeNobody Thanks for the report. Did you run this in a fresh Node.js project, or in a clone of the `node-gtk` git repository?

**Comment by PopeNobody** [comment]
In the node-gtk repository thus far.  next step is to figure out how to use it to generate quote images for some of my favorite authors.

This kind of thing.

![mal-black-owned-business](https://user-images.githubusercontent.com/63942640/219848487-443f5430-1bc0-4e15-80bb-35f019c03db7.png)

These used to be all over the place from ixquotes and izquotes, to it's hard to find any good ones these days.

**Comment by romgrk** [comment]
Could you post an install log so we see what's going wrong? And the commands you're using to install as well.

**Comment by PopeNobody** [comment]
The problem is solved, but basically, either I misread, or the docs said to clone the repository, and then do a "npm install node-gtk".

Which, of course, does not make sense, it would install the version from the npm repository, not build the version from github.  So the fix was to do "npm install", instead.
