### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by systemd11** [romgrk/node-gtk#347]
am trying to install node-gtk on my Nobara (Fedora 37 Base) machine. I followed the below steps to install the necessary dependencies:

Installed gtk3-devel, nodejs, npm, gcc-c++, make, glib2-devel, cairo-devel, pango-devel, libjpeg-turbo-devel, giflib-devel, librsvg2-devel, libtiff-devel, libpng-devel, and libwebp-devel using the command sudo dnf install -y gtk3-devel nodejs npm gcc-c++ make glib2-devel cairo-devel pango-devel libjpeg-turbo-devel giflib-devel librsvg2-devel libtiff-devel libpng-devel libwebp-devel.
Installed node-gyp globally using the command sudo npm install -g node-gyp.
Tried installing node-gtk globally using the command sudo npm install -g node-gtk. However, I encountered errors during the installation process.
I have attached two text files error1.txt and error2.txt that show the errors I encountered when I tried installing node-gtk. I ran the following command:

npm install node-gtk (errors.txt)
npm install --save node-gtk (errors.txt (In section 2)
[errors.txt](https://github.com/romgrk/node-gtk/files/11183071/errors.txt)
[errors.txt](https://github.com/romgrk/node-gtk/files/11183072/errors.txt)
) (I tried without the --save argument as well)
Additionally, I ran the command node-gyp rebuild after installing node-gyp but before installing node-gtk.

Could you please help me with resolving these Issues?

**Comment by BraidenPsiuk** [comment]
Same here, not able to fallback and build with "npm i node-gtk". My machine info: Debian GNU/Linux 12 (bookworm) x86_64, GNOME 43.4. I installed all recommended dependencies per the README.md...
I noticed these two suspicious lines:
```shell
npm ERR! node-pre-gyp http GET https://node-gtk-1.s3.amazonaws.com/node_gtk/v0.11.0/node_gtk-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://node-gtk-1.s3.amazonaws.com/node_gtk/v0.11.0/node_gtk-node-v108-linux-x64.tar.gz
```

**Comment by romgrk** [comment]
Can you confirm the version numbers? (nodejs in particular)

**Comment by BraidenPsiuk** [comment]
Both of my machines have Nodejs v18.13.0 (official Debian nodejs apt package) installed

**Comment by romgrk** [comment]
I've published v0.12.0 just now, with prebuilt binaries for linux & node 16, 18 only.

The macOS binaries [have failed](https://github.com/romgrk/node-gtk/actions/runs/5398030247/jobs/9803408698), GHA isn't super reliable on macOS. I can try re-running them in a few days, maybe the casks will be fixed.

**Comment by mariusrak** [comment]
I have same problem. The interesting line in error is
```
npm ERR! node-pre-gyp ERR! install response status 403 Forbidden on https://node-gtk-1.s3.amazonaws.com/node_gtk/v0.12.0/node_gtk-node-v93-linux-arm64.tar.gz
```
When I load the url I really get AccesDenied

**Comment by romgrk** [comment]
Please always post you full versions (OS + nodejs + node-gtk) when you report something like this. It's likely that we don't generate a prebuilt binary for your versions.

**Comment by romgrk** [comment]
In this case, we don't generate a binary for you CPU architecture, we only have x86_64. Not sure if GHA does ARM now. In any case, it should fallback to build from source. Is that also failing?

**Comment by mariusrak** [comment]
It just failed with that message, so guess the build step didn't work.

**Comment by romgrk** [comment]
Does it work manually? Run `npm run build` to confirm.

**Comment by romgrk** [comment]
Closing, stale. Open a new issue with versions & logs if you have a problem to report.
