### ISSUE TITLE
NPM installation fails

### ISSUE THREAD

**Issue by FooterManDev** [romgrk/node-gtk#361]
https://gist.github.com/FooterMan15/7cbd4b07dc413245e3d4bf5733c397b7
When running `npm i node-gtk`, NPM fails to install and errors.

Arch Linux (EndeavourOS) 6.7.8
NodeJS 21.7.1

**Comment by romgrk** [comment]
Can't reproduce and the gist link doesn't work for me, 404.

![image](https://github.com/romgrk/node-gtk/assets/1423607/4bd9ad70-057d-444a-bbce-b57c09236cb0)

**Comment by FooterManDev** [comment]
The gist link expired because it was made 12 days before your response.
I am now able to install node-gtk, though I don't know why. I just tried it and it worked :shrug:
