### ISSUE TITLE
Support multiple return values

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#4]
Function calls have a `return-value`, but they also have C-style `out-parameters`. 
`out-parameters` can also `allow-none`. And some parameters might be skippable.

https://wiki.gnome.org/Projects/GTK%2B/DocumentationSyntax/Annotations/Examples#A.27out.27_parameters

**Comment by romgrk** [comment]
Use case:
```c
void gtk_widget_get_size_request (GtkWidget *widget,
                             gint *width,
                             gint *height);
```
Has 2 out-parameters, `width` and `height`. This needs to be translated to be understandable to JS, which does not understand pointers, nor multiple return values;
 - Possibility 1: return 
```js 
[width, height]
```
 - Possibility 2: return 
```js
{"width": width, "height": height}
```

**Comment by benwaffle** [comment]
2nd is probably better so we rely on name and not index:

`ret.width`, not `ret[0]`

**Comment by romgrk** [comment]
Yes, I was leaning towards that option. Haven't had the time to check how GJS handles this. It might be good to be somewhat compatible with GJS implementation.

**Comment by romgrk** [comment]
https://github.com/romgrk/node-gtk/blob/master/tests/function_call__multiple_return.js

**Comment by romgrk** [comment]
Cases:

 - [ ] **void return, 1 out-argument:**
  Example: TODO
  easy case, use out-argument as return value

 - [ ] **void return, 2+ out-arguments:** 
  Example: [gtk_widget_get_size_request](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-get-size-request)
  still easy, return an object with arg names as keys, e.g. `{ width: 100, height: 70 }`

 - [ ] **non-void return, 1 out-argument:**
  Example: [json_serialize_gobject](https://developer.gnome.org/json-glib/stable/json-glib-GObject-Serialization.html#json-serialize-gobject), [g_ascii_string_to_unsigned](https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-ascii-string-to-unsigned)
  This one is tricky, in some cases we care more about the return value (`json_serialize_gobject`), in other cases we care more about the out-argument (`g_ascii_string_to_unsigned`).
  A possible solution would be to return the value that encodes the more information, e.g. string > number > boolean. Also, if there is a way to find if one of them is the array-length of the other, we know we can ignore it.

 - [ ] **non-void return, 1 out-argument, 1 array-length out-argument:**
  Example: [g_file_get_contents](https://developer.gnome.org/glib/stable/glib-File-Utilities.html#g-file-get-contents)
  For this particular example, the `length` out-argument should be detected as an array-length and be removed from the count of returnable out-arguments. It would fall back into the previous category (non-void return, 1 out-argument)
  
 - [ ] **non-void return, 2+ out-arguments:**
  Example: [g_bookmark_fil_get_app_info](https://developer.gnome.org/glib/stable/glib-Bookmark-file-parser.html#g-bookmark-file-get-app-info), [g_io_channel_read_chars](https://developer.gnome.org/glib/stable/glib-IO-Channels.html#g-io-channel-read-chars)
  For these cases, the return value is not of utmost importance and could be ignored, thus allowing us to return an object with arg names as keys. But are there cases of these with important return values?

**Comment by romgrk** [comment]
Following comments from Emmanuele Bassi (@ ebassi) on IRC, it's been noted that PyGObject returns an array as `[retval, out1, out2, ...]` for more than 1 return value, and that API niceness is added through overrides.
Example: https://gitlab.gnome.org/GNOME/pygobject/blob/master/gi/overrides/__init__.py#L331-350

**Comment by benwaffle** [comment]
In JS we could also de-structure the object:

```js
const { width, height } = widget.sizeRequest()
```

**Comment by romgrk** [comment]
I totally agree with you, the exposed API will be in the form you're describing.

The thing is, the words that Emmanuele used after reading my summary of cases above were something about being "headed to a disaster", if following the original plan. He pointed that in PyGObject, more than 1 return values are always returned as an array, but the exposed API is modified through overrides ([which we also have](https://github.com/romgrk/node-gtk/blob/master/lib/overrides/GLib.js)).

So the C++ side would not handle any fancy stuff, which is good.
In the JS side, we'd need something like:
```js
exports.apply = function(Gtk) {
  const originalGetSizeRequest = Gtk.Widget.prototype.getSizeRequest
  Gtk.Widget.prototype.getSizeRequest = function() {
    const [width, height] = originalGetSizeRequest.call(this)
    return { width, height }
  }
};
```

I've committed just now the [changes](https://github.com/romgrk/node-gtk/commit/0a423692f5701f17629bd5c2738fe41caa7245dc) to return an array with multiple values, I still need to fix one issue with caller-allocated out-arguments and we should be good to implement the overrides and close this (finally!).

**Comment by benwaffle** [comment]
why not just build an JS object in c++?

**Comment by romgrk** [comment]
I'll be pasting here the conversation with Emmanuele, for reference:
```
ebassi 16:51:38
romgrk: Have you looked at gjs?
2) sounds like a recipe for disaster
GJS returns an array, not a named object
You cannot really count on the name of the argument being sensible
Some APIs use things like "width_out" or "width_p" for out arguments
3) Same applies for entry points that return non-void (typically a boolean)
Python, GJS, and Perl use (retval, out_arg1, out_arg2, ...)
Python uses overrides to mask the retval

ebassi 16:55:30
romgrk: So, I'd strongly encourage you to always return an array with the first element being the retval, if not `void`, followed by all in-out arguments, followed by the out arguments
Which is what every other binding does
If you want to make the API look nicer for your specific language/stack, use an override
But make sure to document it

ebassi 16:58:20
https://gitlab.gnome.org/GNOME/pygobject/blob/master/gi/overrides/__init__.py#L331-350
```

So basically, handling stuff on the JS side allows us a more fine-grained control over the exposed API. We can also handle cases that are not covered by GI annotations, as 
1. boolean return values which indicate failure:
 - https://gitlab.gnome.org/GNOME/gjs/issues/68
 - https://gitlab.gnome.org/GNOME/gobject-introspection/issues/63
 - [PyGObject strips those using overrides](https://gitlab.gnome.org/GNOME/pygobject/blob/master/gi/overrides/__init__.py#L331-350)
2. Useless string length arguments:
 - https://gitlab.gnome.org/GNOME/gjs/issues/66

Also, the complexity on the C++ side is already bad. 
The speed benefits that *could* (not guaranteed) be gained are not worth it, because these cases are edge cases.
Overrides are less elegant (it's a hack) than a C++ side solution, but it's the only way to get a sane solution (re-read https://github.com/romgrk/node-gtk/issues/4#issuecomment-399326105, if you can find a sane solution to those cases, I'd be happy to hear).
Splitting the problem half-way (handling easy cases in C++ & hard cases in JS) would split the logic, which hurts maintainability of the project.

Let me know what you think, basically I'm also trying to convince myself because I'm not sure which one is the better solution.
