### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by benwaffle** [romgrk/node-gtk#47]
Personally, i prefer circleci, but travis is fine too

**Comment by romgrk** [comment]
Yes, I was looking into that just yesterday! I've never setup any CI though, so if you have suggestions or PRs, they're always welcome.

**Comment by benwaffle** [comment]
You want the CI to upload releases to github? to npm?

**Comment by romgrk** [comment]
It [might be possible](https://github.com/mapbox/node-pre-gyp#7-automate-builds) to automate node-pre-gyp pre-built binaries with TravisCI.
The pre-built binaries are usually stored in Amazon S3 buckets, but [node-pre-gyp-github](https://www.npmjs.com/package/node-pre-gyp-github) also exists to store them in github releases. I think storing them in github would be ok for now.

For the CI, I've done some reading and I've concluded that TravisCI is a better match for this project overall. CircleCI is easier to setup, but doesn't provide a macOS option for free accounts.

**Comment by benwaffle** [comment]
Why are you using gcc 7?

**Comment by romgrk** [comment]
That's what the "Getting started" was showing :) Tbh I started writing the .travis.yml at 3am and got bored before I could finish it. It's not done yet, and the macOS build still needs to be configured.

**Comment by romgrk** [comment]
CI is completed and works with Node 7, 8 & 9 for linux and macOS. Pre-built binaries are auto-published by travis when including in the commit message `[publish binary]` or `[republish binary]`.

**Comment by benwaffle** [comment]
how about node 10?

**Comment by romgrk** [comment]
My bad, not 7, 8 & 9: supported versions are 8, 9 & 10.

Binaries are published to an amazon S3 bucket specified in package.json. This is all managed by node-pre-gyp, so an `npm install node-gtk` should now fetch the appropriate binary from the bucket (e.g. https://s3.amazonaws.com/node-gtk-1/node_gtk/v0.2.0/node_gtk-node-v64-darwin-x64.tar.gz). There is always a fallback to build in case something goes wrong.
