### ISSUE TITLE
debug.h missing

### ISSUE THREAD

**Issue by Arood** [romgrk/node-gtk#7]
Hi, tried to test your fork after [this discussion](https://github.com/WebReflection/node-gtk/issues/29) but can't build it, seems like some files are missing? Right now it can't find debug.h, which doesn't seem to have been added to the repo.

**Comment by romgrk** [comment]
Totally forgot, I've been using a gitlab repo lately. I've pushed my latest changes, hopefully it will compile right.
Specific differences from the original repo:
```js
const gi = require('node-gtk');
Gtk = gi.require('Gtk', '3.0');
Gtk.init(); // or Gtk.init(null, 0)
var win = new Gtk.Window();
win.toString(); // => '[GtkWindow: 0x37d2280]'
win.setDefault.toString() // => 'function gtk_window_set_default (default_widget:interface): void { [GObject code] }'
```
Function names are camelCase, properties are snake_case. 
When I want to do some exploration, I `npm run inspect`. It starts a REPL with `gi`, `gtk` and `gdk` objects, which each have `.methods`, `.constants`, `.fields`, etc. Methods have some info about their arguments, return values, etc.

**Comment by romgrk** [comment]
`npm run test` starts a more fully-fledged integration of node/gobject-introspection, `npm run mocha` runs a very limited set of tests.

**Comment by Arood** [comment]
Hello! Tried running it as a module now, and that seems to work! Nice with Node 6-support as well. However, I'm still having trouble with getAllocation again. I'm getting a GdkRectangle, but no width or height? Can you try the following code and see if it works for you? Starting to wonder if there's something weird with my Gnome-installation :P

```
var Gtk = require('node-gtk').require('Gtk', '3.0');

Gtk.init();

var win = new Gtk.Window({
  title: 'node-gtk'
});

win.connect('check-resize', function(e) {
  var rect = win.getAllocation();
  console.log(rect, rect.width);
});

win.connect('show', Gtk.main);
win.connect('destroy', Gtk.main_quit);

win.add(new Gtk.Label({label: 'Hello Gtk+'}));

win.showAll();
```

**Comment by romgrk** [comment]
Hello! Tested as well, I get the same result. 

After quick inspection, it seems the problem is that when 'Gtk' is loaded, 'Gdk' isn't; `GdkRectangle` being part of the `Gdk` namespace, it's prototype is never defined until you require `Gdk` (3.0) namespace.

I've pushed a few changes (320de99bc1f2bf781584338d9b32c9514ba0ca84), the `gi.require` function now loads all the immediate dependencies of a given module upon loading it. 
It does add a good second or two to the startup process for a module as big as Gtk, but that's arguably inevitable. Unless doing some smart lazy loading. But that's not for now.

**Comment by romgrk** [comment]
There is also some limited support for 
```js
class GWin extends Gtk.Window { 
  constructor() {
    super();
  }
}
```
but the prototype doesn't seem to be extended correctly; you end up with a `Gtk.Window`. 
I also have to check the problem with C *out* parameters, which where your initial concern I think. Eg. the `window#getSize(*width, *height)` in C receives two pointers to integers as arguments, and that must be translated to JS as `window#getSize(void): {width, height}`
