### ISSUE TITLE
Assert that Gtk.Builder works

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#75]
See https://gist.github.com/carlos-jenkins/8923124

**Comment by cedlemo** [comment]
do you want an example of `Gtk.Builder` or some tests or both ?

**Comment by romgrk** [comment]
Sure, both would be nice! First, we'd need a basic example, just to showcase how to do it. I usually create examples by translating some pygobject code into node-gtk code.
Then, if this example does not work for some reason (it might segfault), we'll need to add a minimal regression test and make it pass (well, I will need to fix whatever bug I've made).

**Comment by cedlemo** [comment]
Ok I think can do this, I already know how to do it in C and ruby, it is just that I am not really used to javascript but I want to learn it.

**Comment by romgrk** [comment]
Closed by #78
