### ISSUE TITLE
Project name is too specific maybe?

### ISSUE THREAD

**Issue by k0d** [romgrk/node-gtk#81]
This is a pretty obvious question, but as this works well with other GIR libraries, maybe it shouldn't be called Node-Gtk?

**Comment by romgrk** [comment]
Yes, it's a reflection that I already had. The best name would be `node-gir`, but well, it's taken.
I'm open to a better name, but it would have to be clearly better because switching a project name has a cost.

**Comment by benwaffle** [comment]
Maybe @place1 is willing to give the name node-gir? although he/she did work on it in June

**Comment by k0d** [comment]
@benwaffle That's not likely to happen as he wants to keep that project and wouldn't change the name just because we want the better one ;)

**Comment by romgrk** [comment]
Agreed. I think it would also be a bad idea for a project to re-use a different project name. I know both projects are still pre 1.0 (and thus semver doesn't disallow breaking changes like that one), but switching npm package names is bad for users of both projects.

**Comment by romgrk** [comment]
Closing because I can live with the current name.
