### ISSUE TITLE
Implement get/set of non-introspected properties

### ISSUE THREAD

**Issue by k0d** [romgrk/node-gtk#83]
We could expose internal.ObjectProperty(g/s)etter, but it'd be better to use the JS Proxy API I think.

I'll work on this issue as I have a possible solution in mind.

**Comment by romgrk** [comment]
Proxy API is new and shiny, but it's not necessarily what we want/need. For example, we wouldn't want to turn all our objects into proxies if it's to satisfy a 0.1% use-case. Usually, I prefer simpler solutions unless there are strong benefits to a more complex solution.

**Comment by k0d** [comment]
We can do it with NAN_PROPERTY_SETTER(property_set_handler) instead....am close to being done with the code for this.

**Comment by romgrk** [comment]
Reopen if needed.
