### ISSUE TITLE
Issues with Pixbuf

### ISSUE THREAD

**Issue by LyrantheR** [romgrk/node-gtk#96]
I apologize if this is out of context in any way.
I've spent about 3 hours now trying to get a pixbuf out of my images to no avail. Might be attributed to the lack of documentation, but I would appreciate it if anyone could advise me on what to do or what the issue is.

**Comment by romgrk** [comment]
Hey, no problem at all. So regarding documentation, what I would usually advise is to look at the C documentation, or any gobject-introspection documentation such as the [PyGObject](https://lazka.github.io/pgi-docs/) one.

Keep in mind that node-gtk is basically just bindings from C to Javascript, so for example, if you wanted to call the C method [gdk_pixbuf_new_from_file(const char*filename, GError error)](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-File-Loading.html#gdk-pixbuf-new-from-file), you would use the JS function `GdkPixbuf.Pixbuf.newFromFile(filename)`, which does nothing more than translating your JS values into C values.

**Note**: actually, it does a bit more than just translating your values. Our example, `gdk_pixbuf_new_from_file`, takes an error out-argument. This argument is not necessary in JS; node-gtk will fill it and an error will be thrown if one arises. Some other C idioms are also taken care of, such as passing an array length as an additional argument: this is susally filled by node-gtk.

As a summary, I would recommend you to find for a C example of what you're trying to do, then translate it into javascript. I it also possible to translate PyGObject examples into javascript, usually only the naming conventions will change, and it's maybe easier than starting from a C example.

If you can post an example of what you're trying to achieve, I can maybe assist you.

**Comment by LyrantheR** [comment]
Oddly enough, I was just trying to get an image widget and suddenly Gtk.Image.newFromFile started working properly. On the other hand, I had tried GdkPixbuf.Pixuf.newFromFile and it gave me an error! Im starting to get the hang of this. Thank you very much anyway
